# Generated by Django 5.2.13 on 2026-04-09 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BATCH_CLEANED', 'Batch Cleaned'), ('BATCH_FAILED', 'Batch Failed'), ('FEATURES_ENGINEERED', 'Features Engineered'), ('TRANSACTION_ASSESSED', 'Transaction Assessed'), ('INTEGRITY_VIOLATION', 'Integrity Violation'), ('DECISION_MADE', 'Decision Made'), ('FEEDBACK_SUBMITTED', 'Feedback Submitted'), ('RULE_WEIGHTS_UPDATED', 'Rule Weights Updated'), ('THRESHOLDS_UPDATED', 'Thresholds Updated'), ('CHAIN_VIOLATION', 'Chain Violation')], max_length=30)),
                ('entity_id', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('previous_hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64)),
                ('current_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_batches', models.IntegerField(default=0)),
                ('batches_processed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'datasets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('ALLOWED', 'Allowed'), ('REVIEW', 'Review'), ('BLOCKED', 'Blocked')], max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('threshold_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'decisions',
            },
        ),
        migrations.CreateModel(
            name='FraudRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('rule_config', models.JSONField(default=dict)),
                ('weight', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('integrity_hash', models.CharField(max_length=64)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fraud_rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RejectedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_row', models.JSONField()),
                ('rejection_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_transactions', to='pipeline.dataset')),
            ],
            options={
                'db_table': 'rejected_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_before', models.FloatField(blank=True, null=True)),
                ('weight_after', models.FloatField(blank=True, null=True)),
                ('threshold_before', models.FloatField(blank=True, null=True)),
                ('threshold_after', models.FloatField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pipeline.fraudrule')),
            ],
            options={
                'db_table': 'rule_versions',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='pipeline.auditlog')),
            ],
            options={
                'db_table': 'security_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('merchant_id', models.CharField(db_index=True, max_length=255)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='SIM', max_length=10)),
                ('transaction_type', models.CharField(max_length=20)),
                ('step', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('location_metadata', models.JSONField(default=dict)),
                ('is_outlier', models.BooleanField(default=False)),
                ('ground_truth_label', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pipeline.dataset')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('ml_score', models.FloatField(default=0.0)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('triggered_rules', models.JSONField(default=list)),
                ('rule_weights_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='pipeline.transaction')),
            ],
            options={
                'db_table': 'risk_assessments',
            },
        ),
        migrations.CreateModel(
            name='ReviewQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=10)),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('claimed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pipeline.decision')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pipeline.transaction')),
            ],
            options={
                'db_table': 'review_queue',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HumanFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('FRAUD', 'Fraud'), ('LEGITIMATE', 'Legitimate'), ('UNCERTAIN', 'Uncertain')], max_length=15)),
                ('confidence_score', models.IntegerField()),
                ('notes_encrypted', models.BinaryField(blank=True, null=True)),
                ('feedback_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='pipeline.reviewqueue')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='pipeline.transaction')),
            ],
            options={
                'db_table': 'human_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='decision',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='pipeline.transaction'),
        ),
        migrations.CreateModel(
            name='TransactionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat_amount', models.FloatField()),
                ('feat_old_balance_org', models.FloatField()),
                ('feat_old_balance_dest', models.FloatField()),
                ('feat_hour', models.IntegerField()),
                ('feat_orig_txn_count', models.IntegerField()),
                ('feat_dest_txn_count', models.IntegerField()),
                ('feat_high_amount', models.IntegerField()),
                ('feat_type_cash_in', models.IntegerField()),
                ('feat_type_cash_out', models.IntegerField()),
                ('feat_type_debit', models.IntegerField()),
                ('feat_type_payment', models.IntegerField()),
                ('feat_type_transfer', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pipeline.transaction')),
            ],
            options={
                'db_table': 'transaction_features',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['dataset', 'user_id'], name='transaction_dataset_c6d8ed_idx'),
        ),
    ]
